'use strict';
const fs=require('node:fs'),path=require('node:path'),childProcess=require('node:child_process');
const core=require('./registry.cjs');
const root=path.resolve(__dirname,'../..'),site=path.join(root,'vertex/dist');
const sha=/^[a-f0-9]{40}$/;
const sourceCommit=(()=>{
  for(const value of [process.env.VISION_SOURCE_COMMIT,process.env.GITHUB_SHA])if(sha.test(value||''))return value;
  try{const value=childProcess.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();if(sha.test(value))return value;}catch{}
  return null;
})();
fs.writeFileSync(path.join(__dirname,'build-info.generated.mjs'),'export const sourceCommit='+JSON.stringify(sourceCommit)+';\n');
const read=name=>fs.readFileSync(path.join(site,name),'utf8');
const put=(name,text)=>fs.writeFileSync(path.join(site,name),text);
core.validate(core.modules);
for(const [source,target] of [['registry.cjs','vision-core.js'],['views-ops.js','vision-views.js'],['views-ops.css','vision-views.css'],['work-center.js','vision-work-center.js'],['work-center.css','vision-work-center.css'],['notifications-center.js','vision-notifications.js'],['notifications-center.css','vision-notifications.css'],['system-status-center.js','vision-system-status.js'],['system-status-center.css','vision-system-status.css'],['session-center.js','vision-session.js'],['session-center.css','vision-session.css'],['taxi-adapter.js','vision-taxi-adapter.js'],['shell.js','vision-shell.js'],['shell.css','vision-shell.css'],['compact.css','vision-compact.css']])put(target,fs.readFileSync(path.join(__dirname,source),'utf8'));
let html=read('index.html');
html=html.replace(/<title>[^<]*<\/title>/,`<title>VERTEX VISION ${core.version} — Vertex Group · Views</title>`);
if(!html.includes('href="vision-shell.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-shell.css"></head>');
if(!html.includes('href="vision-compact.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-compact.css"></head>');
if(!html.includes('href="vision-views.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-views.css"></head>');
if(!html.includes('href="vision-work-center.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-work-center.css"></head>');
if(!html.includes('href="vision-notifications.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-notifications.css"></head>');
if(!html.includes('href="vision-system-status.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-system-status.css"></head>');
if(!html.includes('href="vision-session.css"'))html=html.replace('</head>','<link rel="stylesheet" href="vision-session.css"></head>');
if(!html.includes('src="vision-core.js"'))html=html.replace('</body>','<script src="vision-core.js"></script></body>');
if(!html.includes('src="vision-taxi-adapter.js"'))html=html.replace('</body>','<script src="vision-taxi-adapter.js"></script></body>');
if(!html.includes('src="vision-views.js"'))html=html.replace('</body>','<script src="vision-views.js"></script></body>');
if(!html.includes('src="vision-work-center.js"'))html=html.replace('</body>','<script src="vision-work-center.js"></script></body>');
if(!html.includes('src="vision-notifications.js"'))html=html.replace('</body>','<script src="vision-notifications.js"></script></body>');
if(!html.includes('src="vision-shell.js"'))html=html.replace('</body>','<script src="vision-shell.js"></script></body>');
if(!html.includes('src="vision-system-status.js"'))html=html.replace('</body>','<script src="vision-system-status.js"></script></body>');
if(!html.includes('src="vision-session.js"'))html=html.replace('</body>','<script src="vision-session.js"></script></body>');
put('index.html',html);
const release=JSON.parse(read('release.json'));
Object.assign(release,{version:core.version,revision:core.revision,source_commit:sourceCommit,date:'2026-10-03',platform:core.id,core_version:core.coreVersion,modules:core.modules.map(m=>m.id),active_modules:core.modules.filter(m=>m.status==='active').map(m=>m.id),coming_soon_modules:core.modules.filter(m=>m.status==='coming-soon').map(m=>m.id),mode:'release-candidate',cloud_database_connected:false,unified_apk_hosted:false});
for(const feature of ['VERTEX VISION primary platform','19 registered child modules','Versioned platform registry and API','Explicit adapters preserving existing module data','Vertex Taxi external integration contract','VERTEX Engineers external integration contract'])if(!release.features.includes(feature))release.features.push(feature);
for(const boundary of ['Shared cloud database and real authentication are not connected','Views is the only active Hub module in RC1; every other division is Coming Soon','Registration does not enable a tenant module or imply completed workflows','JARVIS is a separate project','The existing hosted APK link remains the previous published Vertex build until this RC is separately released','Vertex Taxi private state remains outside VISION; integration is API/events only','VERTEX Engineers private state remains outside VISION; integration is API/events only'])if(!release.boundaries.includes(boundary))release.boundaries.push(boundary);
put('release.json',JSON.stringify(release,null,2)+'\n');
const manifest=JSON.parse(read('manifest.webmanifest'));Object.assign(manifest,{name:'VERTEX VISION — Vertex Group',short_name:'VISION',description:'Views и направления Vertex Group в одной платформе. Демонстрационная версия.'});put('manifest.webmanifest',JSON.stringify(manifest,null,2)+'\n');
const UI_CACHE_SUFFIX='interface-14';
let sw=read('sw.js').replace(/const CACHE='[^']+'/ ,`const CACHE='vertex-vision-${core.version.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${core.revision}-${UI_CACHE_SUFFIX}'`);
for(const file of ['vision-core.js','vision-taxi-adapter.js','vision-views.js','vision-views.css','vision-work-center.js','vision-work-center.css','vision-notifications.js','vision-notifications.css','vision-system-status.js','vision-system-status.css','vision-session.js','vision-session.css','vision-shell.js','vision-shell.css','vision-compact.css'])if(!sw.includes("'./"+file+"'"))sw=sw.replace('const ASSETS=[',"const ASSETS=['./"+file+"',");put('sw.js',sw);
put('design-shell.js',read('design-shell.js').replaceAll('1.14-demo',core.version));
// Building web assets does not upload a new APK. Keep the hosted binary's identity explicit.
let mobile=read('mobile.js').replaceAll('Android APK · 1.15-demo ↓','Android APK · 1.14-demo ↓');
mobile=mobile.replace('APK 1.14 доступен по кнопке ниже;',`По кнопке ниже — предыдущий опубликованный APK, не ${core.version};`);
mobile=mobile.replace('APK 1.14 is available below;',`The link below is the previous published APK, not ${core.version};`);
put('mobile.js',mobile);
console.log('Built VISION public assets: '+core.version+' / '+core.modules.length+' modules. No database migrations or deployment performed.');
