/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=vision/wrangler.jsonc --include-runtime=false vision/worker-configuration.d.ts` (hash: 670b31ef7af587581f8119e41e9be7f2)
interface __BaseEnv_Env {
	VISION_ENV: "staging";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./backend/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VISION_ENV">> {}
}
