import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
import {startServer} from '../../.vision-build/portable/desktop-server.mjs';
const evidence=fileURLToPath(new URL('../../.vision-build/evidence/',import.meta.url));
await mkdir(evidence,{recursive:true});
const report={status:'running',checks:[],screenshots:[],nativeAndroidRuntimeTested:false};
const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);};
const app=await startServer({port:0});
const browser=await chromium.launch({headless:true});
const api=(page,profile,path,command)=>page.evaluate(async({profile,path,command})=>{
 const response=await fetch(path,{method:command?'POST':'GET',headers:{'x-vision-profile':profile,'content-type':'application/json'},body:command?JSON.stringify(command):undefined});
 return {status:response.status,body:await response.json()};
},{profile,path,command});
try{
 check('desktop server denies foreign origin',(await fetch(app.url,{headers:{origin:'https://external.invalid'}})).status===403);
 check('desktop server has no exposed demo API',(await fetch(app.url+'/api/profiles')).status===404);
 for(const [label,viewport] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){
  const context=await browser.newContext({viewport});
  const page=await context.newPage();
  const errors=[];const network=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(!request.url().startsWith(app.url+'/'))network.push(request.url());});
  await page.goto(app.url);
  await page.waitForFunction(()=>document.documentElement.dataset.visionReady==='true',{},{timeout:90000});
  await page.waitForFunction(()=>document.querySelector('#profile').options.length===6);
  const config=(await api(page,'guest','/api/profiles')).body;
  check(label+': six synthetic profiles',config.profiles.length===6);
  await page.getByRole('button',{name:'Создать запрос уборки'}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('NEW'));
  let order=(await api(page,'guest','/api/orders')).body[0];
  check(label+': guest creates NEW order',order.status==='NEW'&&order.version===1);
  const command=(type,extra={})=>({type,tenant_id:config.demo.tenant_id,idempotency_key:crypto.randomUUID(),order_id:order.id,expected_version:order.version,...extra});
  check(label+': unassigned staff cannot read order',(await api(page,'staff','/api/orders')).body.length===0);
  check(label+': guest cannot assign staff',(await api(page,'guest','/api/commands',command('assign',{assignee_user_id:config.demo.staff_id}))).status===403);
  await page.selectOption('#profile','views');
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('NEW'));
  check(label+': Views sees guest request',(await api(page,'views','/api/orders')).body.length===1);
  await page.selectOption('#profile','dispatcher');
  await page.getByRole('button',{name:'Назначить сотрудника'}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('ACCEPTED'));
  check(label+': stale order version is rejected',(await api(page,'staff','/api/commands',command('start'))).status===409);
  await page.selectOption('#profile','staff');
  await page.getByRole('button',{name:'Начать',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('IN_PROGRESS'));
  await page.getByRole('button',{name:'На проверку',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('QUALITY'));
  order=(await api(page,'staff','/api/orders')).body[0];
  check(label+': assignee cannot self-approve',(await api(page,'staff','/api/commands',command('pass'))).status===403);
  await page.selectOption('#profile','quality');
  await page.getByRole('button',{name:'На доработку',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('IN_PROGRESS'));
  await page.selectOption('#profile','staff');
  await page.getByRole('button',{name:'На проверку',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('QUALITY'));
  await page.selectOption('#profile','quality');
  await page.getByRole('button',{name:'Принять',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('COMPLETED'));
  order=(await api(page,'quality','/api/orders')).body[0];
  check(label+': full flow including rework completes',order.status==='COMPLETED'&&order.version===7);
  const audit=(await api(page,'audit','/api/audit')).body;
  check(label+': seven committed audit events only',audit.length===7&&audit.some(e=>e.action==='quality.rejected')&&audit.some(e=>e.action==='quality.passed'));
  check(label+': guest cannot read audit',(await api(page,'guest','/api/audit')).body.length===0);
  await page.selectOption('#profile','audit');
  await page.waitForFunction(()=>document.querySelector('#rows').textContent.includes('quality.passed'));
  check(label+': no document horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:evidence+label+'.png',fullPage:true});
  report.screenshots.push(label+'.png');
  const create={type:'create',tenant_id:config.demo.tenant_id,idempotency_key:crypto.randomUUID(),customer_id:config.demo.customer_id,requester_organization_id:config.demo.views_id,service_id:config.demo.service_id};
  const first=await api(page,'guest','/api/commands',create);
  const retry=await api(page,'guest','/api/commands',create);
  check(label+': retry returns original response',first.status===200&&JSON.stringify(first)===JSON.stringify(retry));
  const changed=await api(page,'guest','/api/commands',{...create,service_id:'11111111-1111-4111-8111-111111111111'});
  check(label+': changed retry conflicts',changed.status===409);
  check(label+': external fetch is blocked',(await page.evaluate(async()=> (await fetch('https://external.invalid/api/orders')).status))===403);
  const second=await context.newPage();
  await second.goto(app.url);
  await second.waitForFunction(()=>document.documentElement.dataset.visionReady==='error');
  check(label+': concurrent database tab fails safely',(await second.locator('#message').innerText()).includes('другой вкладке'));
  await second.close();
  await page.reload();
  await page.waitForFunction(()=>document.documentElement.dataset.visionReady==='true',{},{timeout:90000});
  await page.waitForFunction(()=>document.querySelector('#profile').options.length===6);
  const persisted=(await api(page,'guest','/api/orders')).body;
  check(label+': two orders survive reload without duplication',persisted.length===2&&persisted.some(o=>o.id===order.id&&o.status==='COMPLETED'));
  check(label+': no external network requests',network.length===0);
  check(label+': no page JavaScript errors',errors.length===0);
  await context.close();
 }
 report.status='passed';
 console.log(JSON.stringify(report,null,2));
}catch(error){report.status='failed';report.error=error.stack;console.error(error);process.exitCode=1;}
finally{await browser.close();await app.close();await writeFile(evidence+'portable-tests.json',JSON.stringify(report,null,2));}
