const NAV=[
["dashboard","⌂","Dashboard"],["projects","▤","Projects"],["equipment","◫","Equipment"],
["service","⚙","Service"],["team","◎","Team"],["documents","▱","Documents"]
];
const TITLES=Object.fromEntries(NAV.map(([id,,label])=>[id,label]));
const q=s=>document.querySelector(s);
const nav=q("#nav"),content=q("#content"),title=q("#pageTitle"),dialog=q("#actionDialog");
const primary=(label,action="new")=>'<button class="primary" data-action="'+action+'">'+label+"</button>";
const empty=(icon,heading,text,cta)=>'<div class="empty-state"><div class="empty-icon">'+icon+'</div><h3>'+heading+'</h3><p>'+text+'</p>'+(cta?primary(cta):"")+"</div>";

function dashboard(){
 const stages=["Lead","Survey","Design","Estimate","Contract","Procurement","Installation","QA/QC","Commissioning","Handover","Warranty"];
 return '<div class="hero"><div class="hero-card"><span class="hero-tag">CONSTRUCTION • ELEVATORS • HVAC / MEP • SERVICE</span><h2>Инженерная компания в одном понятном рабочем пространстве.</h2><p>Проект → оборудование → сервис → специалист → документы и история. Без лишних разделов и дублирования.</p></div><div class="quick-card"><h3>Быстрые действия</h3><div class="quick-actions"><button class="quick-action" data-action="project">＋ Новый проект</button><button class="quick-action" data-action="equipment">＋ Добавить оборудование</button><button class="quick-action" data-action="service">＋ Создать сервисную заявку</button></div></div></div>'+
 '<div class="grid"><article class="card"><span class="label">Projects</span><div class="metric empty">Нет данных</div><p>Проекты появятся после подключения staging database.</p></article><article class="card"><span class="label">Equipment</span><div class="metric empty">Нет данных</div><p>Лифты и HVAC используют одну понятную карточку оборудования.</p></article><article class="card"><span class="label">Service</span><div class="metric empty">Нет заявок</div><p>Плановые, аварийные и пусконаладочные работы.</p></article><article class="card wide"><h3>Проектный цикл</h3><p>Один последовательный процесс для строительных и инженерных проектов.</p><div class="steps">'+stages.map(x=>'<div class="step">'+x+"</div>").join("")+'</div></article><article class="card"><span class="label">Integration</span><div class="metric">0.2</div><p>VISION staging registered. Production не включён.</p></article></div>';
}
function projects(){return '<div class="section-head"><div><p class="eyebrow">WORK</p><h2>Projects</h2><p>Все строительные и инженерные проекты в одном месте.</p></div>'+primary("+ Новый проект","project")+'</div><div class="notice">Проект содержит обзор, объект/клиента, этап, смету, оборудование, задачи, документы и историю.</div><div style="margin-top:18px">'+empty("▤","Проектов пока нет","Runtime 0.2 готов к проектам. Реальные записи появятся после подключения проверенной staging persistence.","Создать проект")+"</div>";}
function equipment(){const filters=["Все","Лифты","Вентиляция","Отопление","Кондиционирование","Другое"];return '<div class="section-head"><div><p class="eyebrow">ASSETS</p><h2>Equipment</h2><p>Единый реестр инженерного оборудования.</p></div>'+primary("+ Оборудование","equipment")+'</div><div class="filter-row" style="margin-bottom:18px">'+filters.map((x,i)=>'<span class="chip '+(i===0?"active":"")+'">'+x+"</span>").join("")+'</div>'+empty("◫","Оборудование пока не добавлено","Здесь будут лифты, вентиляция, отопление и кондиционирование. У каждой единицы — объект, модель/серийный номер, статус, гарантия, сервис и документы.","Добавить оборудование");}
function service(){return '<div class="section-head"><div><p class="eyebrow">OPERATIONS</p><h2>Service</h2><p>Один сервисный центр для всего инженерного оборудования.</p></div>'+primary("+ Заявка","service")+'</div><div class="grid"><article class="card"><span class="label">Open</span><div class="metric empty">Нет заявок</div><p>Новые обращения и неисправности.</p></article><article class="card"><span class="label">In progress</span><div class="metric empty">Нет работ</div><p>Назначенные и выполняемые работы.</p></article><article class="card"><span class="label">Completed</span><div class="metric empty">Нет истории</div><p>Закрытые работы с инженером и результатом.</p></article></div><div style="margin-top:18px">'+empty("⚙","Сервисных заявок нет","Типы: preventive, corrective, emergency, inspection и commissioning.","Создать заявку")+"</div>";}
function team(){return '<div class="section-head"><div><p class="eyebrow">PEOPLE</p><h2>Team</h2><p>Специалисты, направления и квалификационные документы.</p></div>'+primary("+ Специалист","team")+'</div>'+empty("◎","Команда пока не подключена","Один каталог специалистов: роль, специализации, лицензии/сертификаты, сроки действия и назначенные работы.","Добавить специалиста");}
function documents(){return '<div class="section-head"><div><p class="eyebrow">FILES & COMPLIANCE</p><h2>Documents</h2><p>Все документы проекта и оборудования в одном центре.</p></div>'+primary("+ Документ","document")+'</div><div class="list"><div class="list-row"><div><strong>Contracts</strong><small>Договоры и приложения</small></div><span>Project</span><span>—</span><span class="badge">EMPTY</span></div><div class="list-row"><div><strong>Estimates</strong><small>Сметы и версии</small></div><span>Project</span><span>—</span><span class="badge">EMPTY</span></div><div class="list-row"><div><strong>Design & Drawings</strong><small>Проекты, схемы и чертежи</small></div><span>Engineering</span><span>—</span><span class="badge">EMPTY</span></div><div class="list-row"><div><strong>Licenses & Certificates</strong><small>Документы компании и специалистов</small></div><span>Compliance</span><span>—</span><span class="badge">EMPTY</span></div><div class="list-row"><div><strong>Commissioning & Service</strong><small>Акты и сервисные отчёты</small></div><span>Equipment</span><span>—</span><span class="badge">EMPTY</span></div></div>';}
const renderers={dashboard,projects,equipment,service,team,documents};
function render(id){const page=renderers[id]?id:"dashboard";location.hash=page;title.textContent=TITLES[page];content.innerHTML=renderers[page]();nav.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));q(".sidebar").classList.remove("open");}
nav.innerHTML=NAV.map(([id,icon,label])=>'<button class="nav-item" data-page="'+id+'"><span class="nav-icon">'+icon+'</span><span>'+label+"</span></button>").join("");
nav.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)render(b.dataset.page);});
document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const action=b.dataset.action;const copy={new:["Создать","Выберите нужный раздел: проект, оборудование или сервис."],project:["Новый проект","Форма будет подключена к POST /projects после staging identity/persistence adapter."],equipment:["Новое оборудование","Лифты и HVAC используют существующие asset endpoints. Реальные записи пока не создаются из этого preview."],service:["Новая заявка","Форма будет использовать POST /work-orders после staging подключения."],team:["Новый специалист","Team persistence/API ещё не активированы в runtime 0.2."],document:["Новый документ","Document storage ещё не активирован в runtime 0.2."]}[action]||["Действие","Функция готовится."];q("#dialogTitle").textContent=copy[0];q("#dialogText").textContent=copy[1];dialog.showModal();});
q("#menuButton").addEventListener("click",()=>q(".sidebar").classList.toggle("open"));
window.addEventListener("hashchange",()=>render(location.hash.slice(1)));
render(location.hash.slice(1)||"dashboard");
