import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {PGlite} from "@electric-sql/pglite";
import {createPostgresRepository} from "../src/adapters/postgres-repository.mjs";
import {createEngineersService} from "../src/application/engineers-service.mjs";
import {createMemoryEventSink} from "../src/adapters/memory-repository.mjs";
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,"..");
const schema=fs.readFileSync(path.join(root,"database/schema-v1.sql"),"utf8");
const scope={tenant_id:"t-rc",organization_id:"o-rc",event_id:"evt-1",correlation_id:"corr-1",occurred_at:"2026-10-01T00:00:00Z"};
test("persistent E2E project to completed service",async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec(schema);
 await db.query("insert into engineers_technicians(tenant_id,organization_id,id,name) values($1,$2,$3,$4)",["t-rc","o-rc","tech-1","RC technician"]);
 const repository=createPostgresRepository(db),sink=createMemoryEventSink(),service=createEngineersService({repository,eventSink:sink});
 await service.createProject({id:"p1",tenant_id:"t-rc",organization_id:"o-rc",client_id:"c1",name:"RC project",type:"elevator",created_at:"2026-10-01T00:00:00Z"},scope);
 await service.registerElevator({id:"e1",tenant_id:"t-rc",organization_id:"o-rc",project_id:"p1",status:"installed",manufacturer:null,model:null},{...scope,event_id:"evt-2"});
 await service.commissionAsset("e1","2026-10-02T00:00:00Z",{safe_lift_registration_id:null},{...scope,event_id:"evt-3",occurred_at:"2026-10-02T00:00:00Z"});
 await service.createWorkOrder({id:"wo1",tenant_id:"t-rc",organization_id:"o-rc",asset_id:"e1",type:"preventive",priority:"normal",requested_at:"2026-10-03T00:00:00Z"},{...scope,event_id:"evt-4"});
 await service.transitionWorkOrder("wo1","assigned",{technician_ids:["tech-1"]},{...scope,event_id:"evt-5"});
 await service.transitionWorkOrder("wo1","in_progress",{started_at:"2026-10-03T01:00:00Z"},{...scope,event_id:"evt-6"});
 await service.transitionWorkOrder("wo1","completed",{completed_at:"2026-10-03T02:00:00Z",resolution_summary:"RC maintenance complete"},{...scope,event_id:"evt-7"});
 assert.equal((await repository.projects.list(scope)).length,1);
 assert.equal((await repository.assets.get("e1",scope)).status,"commissioned");
 assert.equal((await repository.workOrders.get("wo1",scope)).status,"completed");
 assert.ok(sink.list().some(e=>e.name==="engineers.maintenance.completed"));
 assert.equal((await repository.projects.list({tenant_id:"other",organization_id:"o-rc"})).length,0);
});
