'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../dist/host-domain.js');
function memory(seed=null){let raw=seed,backup=null;return {fail:false,getItem(){return raw},setItem(k,v){if(this.fail)throw Error('quota');if(k.endsWith('-recovery'))backup=v;else raw=v;},raw:()=>raw,backup:()=>backup};}
const booking=(x={})=>({id:'b1',listingId:'p1',title:'Demo',arrival:'2026-10-12',departure:'2026-10-15',status:'Подтверждено',currency:'USD',total:100,n:3,guests:2,...x});
test('month uses arrival month, not checkout month',()=>assert.equal(D.report({bookings:[booking({arrival:'2026-09-30'})]},{month:'2026-10'}).count,0));
test('currencies never added together',()=>assert.equal(D.report({bookings:[booking(),booking({currency:'UZS',total:1000000})]},{month:'2026-10'}).total,100));
test('null price is visibly unpriced, not zero-rate booking',()=>{const r=D.report({bookings:[booking({total:null})]},{month:'2026-10'});assert.equal(r.priced,0);assert.equal(r.unpriced,1);});
test('pending and cancelled excluded from earnings',()=>assert.equal(D.report({bookings:[booking({status:'Запрос отправлен'}),booking({status:'Отменено'})]}).count,0));
test('property filter narrows report',()=>assert.equal(D.report({bookings:[booking(),booking({listingId:'p2'})]},{property:'p1'}).count,1));
test('monetary summation uses integer minor units',()=>assert.equal(D.report({bookings:[booking({total:.1}),booking({total:.2})]}).total,.3));
test('report snapshots do not expose mutable booking objects',()=>{const b=booking(),r=D.report({bookings:[b]});r.rows[0].total=999;assert.equal(b.total,100);});
test('six months correctly cross year boundary',()=>assert.deepEqual(D.report({bookings:[]},{month:'2026-02'}).months.map(m=>m.key),['2025-09','2025-10','2025-11','2025-12','2026-01','2026-02']));
test('no data does not fabricate ratings or payments',()=>{const r=D.report({bookings:[]});assert.equal(r.count,0);assert.equal(r.total,0);assert.equal(r.reviews,undefined);});
test('CSV quotes commas and embedded quotes',()=>assert.match(D.csv([booking({title:'A, "B"'})]),/"A, ""B"""/));
test('CSV mitigates spreadsheet formula injection',()=>assert.match(D.csv([booking({title:'=1+1'})]),/"'=1\+1"/));
test('staying is half-open: checkout is not a stay',()=>assert.equal(D.filterBookings([booking()],'staying','2026-10-15').length,0));
test('departures can include checkout today',()=>assert.equal(D.filterBookings([booking()],'departures','2026-10-15').length,1));
test('arrivals filter uses exact date',()=>assert.equal(D.filterBookings([booking()],'arrivals','2026-10-12').length,1));
test('save is persistent across repository instances',()=>{const m=memory(),r=D.repository(m);assert.ok(r.save({name:'QA',largeText:true}).ok);assert.equal(D.repository(m).get().name,'QA');});
test('failed persistence does not mutate memory',()=>{const m=memory(),r=D.repository(m);m.fail=true;assert.equal(r.save({name:'Phantom'}).ok,false);assert.equal(r.get().name,'');});
test('malformed storage retained on load and backed up before mutation',()=>{const m=memory('{bad'),r=D.repository(m);assert.equal(m.raw(),'{bad');assert.equal(r.status().damaged,true);assert.ok(r.save({name:'Recovered'}).ok);assert.equal(m.backup(),'{bad');});
test('backup failure leaves corrupt source intact',()=>{const m=memory('{bad'),r=D.repository(m);m.fail=true;assert.equal(r.save({name:'New'}).ok,false);assert.equal(m.raw(),'{bad');});
test('preference snapshot is immutable by caller',()=>{const r=D.repository(memory());r.get().stars.push('x');assert.equal(r.get().stars.length,0);});
test('unrecognized settings and secret-like fields are not stored',()=>{const r=D.repository(memory());r.save({password:'secret',name:'a'.repeat(100)});assert.equal(r.get().password,undefined);assert.equal(r.get().name.length,60);});
test('prototype keys are excluded from notes',()=>{const r=D.normalize(JSON.parse('{"version":1,"notes":{"__proto__":"x","constructor":"y","ok":"z"}}'));assert.deepEqual(r.notes,{ok:'z'});});
test('invalid preference values preserve defaults',()=>assert.equal(D.normalize({version:1,largeText:'yes'}).largeText,false));
test('CSV mitigates formulas with leading whitespace',()=>assert.match(D.csv([booking({title:'  =1+1'})]),/"'  =1\+1"/));
test('read errors refuse subsequent writes to unknown storage',()=>{let wrote=false;const r=D.repository({getItem(){throw Error('read')},setItem(){wrote=true}});assert.equal(r.save({name:'Unsafe'}).ok,false);assert.equal(wrote,false);});
test('capacity overflow refuses instead of silently losing notes',()=>{const r=D.repository(memory());assert.equal(r.save({notes:Object.fromEntries(Array.from({length:501},(_,i)=>['b'+i,'note']))}).ok,false);});
test('language preference accepts only supported values',()=>{const r=D.repository(memory());r.save({language:'en'});assert.equal(r.get().language,'en');});
