'use strict';
const assert = require('node:assert/strict');
const {test} = require('node:test');
const domain = require('../dist/rental-domain.js');
const listing = {id:'qa-apartment', ru:'Демо', en:'Demo', city:'Tashkent', type:'Квартира', price:100, currency:'USD', capacity:2, host:'QA', description:'Local demo'};
const booking = {id:'qa-booking', listingId:listing.id, title:listing.ru, guest:'QA guest', guests:2, arrival:'2026-10-12', departure:'2026-10-15', status:'Подтверждено', total:300, currency:'USD'};
const raw = () => ({favorites:[listing.id], listings:[{...listing}], bookings:[{...booking}], threads:[], blocks:[]});
for (const date of ['2026-02-30','2026-13-01','not-date','2026-1-01','',null,5]) test('reject impossible date '+date,()=>assert.ok(Number.isNaN(domain.dateTime(date))));
test('leap-day date is valid',()=>assert.ok(Number.isFinite(domain.dateTime('2028-02-29'))));
test('night arithmetic does not change at daylight saving',()=>assert.equal(domain.nights('2026-03-07','2026-03-09'),2));
test('today allowed independent of offset',()=>assert.equal(domain.validPeriod('2026-09-29','2026-09-30','2026-09-29'),true));
test('past arrival is rejected',()=>assert.equal(domain.validPeriod('2026-09-28','2026-09-30','2026-09-29'),false));
test('zero night rejected',()=>assert.equal(domain.validPeriod('2026-09-29','2026-09-29','2026-09-29'),false));
test('too-long period rejected',()=>assert.equal(domain.validPeriod('2026-09-29','2027-10-01','2026-09-29'),false));
test('valid data preserved',()=>{const result=domain.normalizeStore(raw());assert.equal(result.rejected,0);assert.equal(result.data.bookings[0].total,300);assert.equal(result.data.listings[0].currency,'USD');});
for(const key of ['listings','bookings','blocks','threads']) test('null '+key+' cannot crash normalization',()=>{const value=raw();value[key].push(null);const result=domain.normalizeStore(value);assert.equal(result.rejected,1);assert.ok(result.data[key].every(Boolean));});
for(const bad of [{},[],3,'malformed']) test('malformed root '+JSON.stringify(bad),()=>assert.ok(domain.normalizeStore(bad).data.bookings));
test('valid records survive alongside invalid ones',()=>{const value=raw();value.bookings.unshift(null,{id:5});assert.equal(domain.normalizeStore(value).data.bookings.length,1);});
test('bad guest count never becomes HTML',()=>{const value=raw();value.bookings[0].guests='<img src=x onerror=alert(1)>';assert.equal(domain.normalizeStore(value).data.bookings.length,0);});
test('invalid currency cannot reach Intl',()=>{const value=raw();value.bookings[0].currency='bad-currency';assert.equal(domain.normalizeStore(value).data.bookings.length,0);});
test('legacy USD is not relabelled as UZS',()=>{const value=raw();delete value.listings[0].currency;delete value.bookings[0].currency;assert.equal(domain.normalizeStore(value).data.bookings[0].currency,'USD');assert.equal(domain.normalizeStore(value).data.listings[0].currency,'USD');});
test('unknown total stays null, not zero',()=>{const value=raw();value.bookings[0].total=null;const data=domain.normalizeStore(value).data;assert.equal(data.bookings[0].total,null);assert.deepEqual(domain.metrics(data.bookings).totals,[]);});
test('duplicate IDs rejected',()=>{const value=raw();value.bookings.push({...booking});assert.equal(domain.normalizeStore(value).data.bookings.length,1);});
test('local IDs cannot shadow confirmed catalog',()=>assert.equal(domain.normalizeStore(raw(),[listing.id]).data.listings.length,0));
test('malformed messages filtered independently',()=>{const value=raw();value.threads=[{listingId:listing.id,messages:[null,{side:'guest',text:'valid',at:'2026-09-29T00:00:00Z'}]}];assert.equal(domain.normalizeStore(value).data.threads[0].messages.length,1);});
test('negative totals rejected',()=>{const value=raw();value.bookings[0].total=-1;assert.equal(domain.normalizeStore(value).data.bookings.length,0);});
test('historical bookings remain in history',()=>{const value=raw();value.bookings[0].arrival='2025-01-01';value.bookings[0].departure='2025-01-02';assert.equal(domain.normalizeStore(value).data.bookings.length,1);});
test('cancelled bookings are inactive',()=>assert.equal(domain.active({...booking,status:'Отменено'}),false));
test('separate currencies never added together',()=>{const result=domain.metrics([booking,{...booking,id:'uzs',currency:'UZS',total:100000}]);assert.deepEqual(result.totals,[['USD',300],['UZS',100000]]);assert.equal(result.confirmedNights,6);});
test('snapshot cannot mutate the application store',()=>{const data=domain.normalizeStore(raw()).data;const copy=domain.snapshot(data,[listing]);assert.throws(()=>{copy.bookings[0].guest='changed';},TypeError);assert.equal(data.bookings[0].guest,'QA guest');});
