import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID as id} from 'node:crypto';import {PGlite} from '@electric-sql/pglite';import {migrate} from '../backend/migrate.mjs';
test('Views UI snapshot preserves RLS, organization scope and honest totals',async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec('create role anon;create role authenticated;');await migrate(db);
 const tenant=id(),org=id(),otherOrg=id(),user=id(),cleaner=id(),property=id(),unit=id(),customer=id(),role=id(),membership=id();
 const insert=(table,fields)=>{const keys=Object.keys(fields);return db.query(`insert into public.vision_${table}(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')})`,Object.values(fields));};
 await insert('tenants',{id:tenant,code:'ui-test',name:'Synthetic UI test'});
 for(const [oid,code] of [[org,'views'],[otherOrg,'other']])await insert('organizations',{id:oid,tenant_id:tenant,code,name:'Synthetic organization',kind:'COMPANY'});
 for(const uid of [user,cleaner])await insert('users',{id:uid,tenant_id:tenant,display_name:'Synthetic operator'});
 await insert('memberships',{id:membership,tenant_id:tenant,user_id:user,organization_id:org});await insert('roles',{id:role,tenant_id:tenant,code:'ui-manager',name:'UI manager'});await insert('membership_roles',{tenant_id:tenant,membership_id:membership,role_id:role});
 await db.query("insert into public.vision_role_permissions(role_id,permission_id) select $1,id from public.vision_permissions where code in ('views.operations.read','views.booking.create','views.booking.manage')",[role]);
 const cm=id(),cr=id();await insert('memberships',{id:cm,tenant_id:tenant,user_id:cleaner,organization_id:org});await insert('roles',{id:cr,tenant_id:tenant,code:'ui-cleaner',name:'Cleaner'});await insert('membership_roles',{tenant_id:tenant,membership_id:cm,role_id:cr});await db.query("insert into public.vision_role_permissions(role_id,permission_id) select $1,id from public.vision_permissions where code='views.cleaning.execute'",[cr]);
 await insert('customers',{id:customer,tenant_id:tenant,display_name:'Synthetic guest'});await insert('views_properties',{id:property,tenant_id:tenant,organization_id:org,code:'test',name:'Synthetic property'});await insert('views_units',{id:unit,tenant_id:tenant,organization_id:org,property_id:property,unit_number:'TEST-001'});
 const booking=id();await insert('views_bookings',{id:booking,tenant_id:tenant,organization_id:org,unit_id:unit,customer_id:customer,public_no:'TEST-B1',check_in:'2026-10-01',check_out:'2026-10-03',created_by:user,total:500});
 async function as(uid,fn){await db.exec('begin;set local role authenticated;');try{await db.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:uid})]);const r=await fn();await db.exec('commit');return r;}catch(e){await db.exec('rollback');throw e;}}
 const snapshot=(uid=user,oid=org,from='2026-10-01',to='2026-10-31')=>as(uid,async()=>(await db.query('select public.vision_views_operations_snapshot($1,$2,$3,$4) data',[tenant,oid,from,to])).rows[0].data);
 await t.test('invoker function respects RLS and exposes only operational fields',async()=>{const s=await snapshot();assert.equal(s.bookings.total,1);assert.equal(s.units.total,1);assert.equal(s.unit_status_counts.READY,1);assert.equal(s.bookings.items[0].id,booking);assert.ok(!('total' in s.bookings.items[0]));assert.ok(!('customer_id' in s.bookings.items[0]));assert.equal(s.modules.filter(m=>m.state==='ACTIVE').length,1);assert.equal(s.modules.find(m=>m.state==='ACTIVE').id,'views');const fn=(await db.query("select prosecdef from pg_proc where proname='vision_views_operations_snapshot'")).rows[0];assert.equal(fn.prosecdef,false);});
 await t.test('same-tenant foreign organization and foreign tenant are denied',async()=>{await assert.rejects(()=>snapshot(user,otherOrg),/forbidden/);await assert.rejects(()=>as(user,()=>db.query('select public.vision_views_operations_snapshot($1,$2,$3,$4)',[id(),org,'2026-10-01','2026-10-31'])),/forbidden/);});
 await t.test('cleaner receives no booking or unit lists and no verification permission',async()=>{const s=await snapshot(cleaner);assert.equal(s.units.available,false);assert.equal(s.bookings.available,false);assert.deepEqual(s.bookings.items,[]);assert.equal(s.cleaning.available,true);assert.ok(!s.permissions.includes('views.cleaning.verify'));});
 await t.test('range is half-open and invalid ranges are rejected',async()=>{assert.equal((await snapshot(user,org,'2026-10-03','2026-10-04')).bookings.total,0);await assert.rejects(()=>snapshot(user,org,'2026-10-01','2026-12-01'),/invalid_date_range/);});
 await t.test('suspended users cannot refresh prior access',async()=>{await db.query("update public.vision_users set status='SUSPENDED' where id=$1",[user]);await assert.rejects(()=>snapshot(),/forbidden/);await db.query("update public.vision_users set status='ACTIVE' where id=$1",[user]);});
 await t.test('200-row bound is explicit while aggregate counts remain accurate',async()=>{await db.query("insert into public.vision_views_units(tenant_id,organization_id,property_id,unit_number) select $1,$2,$3,'SYNTHETIC-'||i from generate_series(1,200) i",[tenant,org,property]);const s=await snapshot();assert.equal(s.units.total,201);assert.equal(s.units.items.length,200);assert.equal(s.units.truncated,true);assert.equal(s.unit_status_counts.READY,201);});
});
