'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../platform/registry.cjs');
const copy=()=>JSON.parse(JSON.stringify(core.modules));
test('VISION is the root and all 19 directions are children',()=>{assert.equal(core.id,'vertex-vision');assert.equal(core.modules.length,19);assert.equal(core.module('views').parent,core.id);assert.ok(core.modules.every(m=>m.parent===core.id));});
test('Views is the only active module and all future divisions are Coming Soon',()=>{assert.equal(core.module('views').status,'active');assert.deepEqual(core.modules.filter(m=>m.status==='active').map(m=>m.id),['views']);assert.ok(core.modules.filter(m=>m.id!=='views').every(m=>m.status==='coming-soon'&&m.actions.length===0));assert.ok(core.modules.every(m=>m.cloudEnabled===false));});
test('registry and nested module definitions are immutable',()=>{assert.ok(Object.isFrozen(core));assert.ok(Object.isFrozen(core.modules));assert.ok(Object.isFrozen(core.module('views').actions));assert.throws(()=>core.modules.push({}),TypeError);});
test('unknown and prototype names never resolve to modules or actions',()=>{for(const id of ['__proto__','constructor','toString','jarvis','']){assert.equal(core.module(id),null);assert.equal(core.canLaunch(id,'host'),false);}assert.equal(core.canLaunch('views','constructor'),false);});
test('duplicates and invalid module IDs are rejected',()=>{const a=copy();a.push(a[0]);assert.throws(()=>core.validate(a),/duplicate/);a.pop();a[0].id='../outside';assert.throws(()=>core.validate(a),/invalid/);});
test('direct business-module dependencies are prohibited',()=>{const a=copy();a[0].dependencies=['cleaning'];assert.throws(()=>core.validate(a),/coupling/);});
test('unverified cloud flags and launch actions in inactive modules are rejected',()=>{const a=copy();a[0].cloudEnabled=true;assert.throws(()=>core.validate(a),/cloud/);const b=copy();b.find(m=>m.id!=='views').actions=['host'];assert.throws(()=>core.validate(b),/inactive/);const d=copy();d.find(m=>m.id!=='views').status='active';assert.throws(()=>core.validate(d),/future/);});
test('readiness identifies RC state without implying working authentication, payments or synchronization',()=>{const r=core.readiness();assert.equal(r.mode,'release-candidate');assert.equal(r.activeModule,'views');assert.equal(r.authenticated,false);assert.equal(r.sharedDatabase,'not-connected');assert.equal(r.productionReady,false);assert.equal(r.payments,false);assert.equal(r.notifications,false);});
test('core exposes the same registry in a classic browser script',()=>{const sandbox={document:{}};vm.runInNewContext(fs.readFileSync('vision/platform/registry.cjs','utf8'),sandbox);assert.equal(sandbox.VertexVisionCore.modules.length,19);assert.equal(sandbox.VertexVisionCore.version,core.version);});
test('public runtime assets exactly match their reviewed source',()=>{for(const [a,b] of [['registry.cjs','vision-core.js'],['views-ops.js','vision-views.js'],['views-ops.css','vision-views.css'],['shell.js','vision-shell.js'],['shell.css','vision-shell.css']])assert.equal(fs.readFileSync('vision/platform/'+a,'utf8'),fs.readFileSync('vertex/dist/'+b,'utf8'));});
test('web and Android both contain the unified core and shell exactly once',()=>{for(const base of ['vertex/dist/','android/app/src/main/assets/site/']){const html=fs.readFileSync(base+'index.html','utf8');for(const asset of ['vision-core.js','vision-views.js','vision-shell.js'])assert.equal(html.split('src="'+asset+'"').length-1,1);assert.equal(JSON.parse(fs.readFileSync(base+'release.json')).version,core.version);}});
test('no local impersonation backend or database runtime is exposed as public assets',()=>{const files=fs.readdirSync('vertex/dist');for(const name of ['dev.mjs','dev.html','dev-ui.js','sandbox.js','pglite.wasm','pglite.data'])assert.ok(!files.includes(name));assert.ok(!fs.readFileSync('vertex/dist/index.html','utf8').includes('/api/profiles'));});
test('database module definitions and canonical registry agree',()=>{const sql=fs.readFileSync('vision/database/migrations/0005_platform_module_registry.sql','utf8');for(const m of core.modules)assert.ok(sql.includes("('"+m.id+"','"));assert.match(sql,/foreign key\(tenant_id,organization_id\)/);assert.match(sql,/default 'REGISTERED'/);});
test('generated platform registry and code are synchronized into Android',()=>{for(const file of ['vision-core.js','vision-views.js','vision-views.css','vision-shell.js','vision-shell.css','index.html','release.json','manifest.webmanifest'])assert.deepEqual(fs.readFileSync('vertex/dist/'+file),fs.readFileSync('android/app/src/main/assets/site/'+file));});

test('only Views can launch from the VISION Hub',()=>{assert.equal(core.canLaunch('views','catalog'),true);for(const m of core.modules.filter(m=>m.id!=='views'))assert.equal(core.canLaunch(m.id,m.actions[0]||'host'),false);});

test('Views operations workspace is the primary active Hub action',()=>{assert.equal(core.module('views').actions[0],'operations');assert.equal(core.canLaunch('views','operations'),true);});
